server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  webflux:
    base-path: /api
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
