server:
  port: ${SERVER_PORT:8030}

spring:
  application:
    name: trainer-workload
  profiles:
    default: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [traceId=%X{traceId:-}] %logger{36} - %msg%n"

management:
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
