server:
  port: ${SERVER_PORT:8020}

spring:
  application:
    name: crm
  profiles:
    default: local
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true

security:
  password:
    length: ${SECURITY_PASSWORD_LENGTH:10}
  jwt:
    secret: ${SECURITY_JWT_SECRET:VGhpcy1pcy1hLWxvY2FsLWRldi1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcyE=}
    expiration: ${SECURITY_JWT_EXPIRATION:1h}

app:
  logging:
    error-appender-name: errorLogAppender

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [transactionId=%X{transactionId:-}] %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,crmmetrics,errorlogs
      path-mapping:
        crmmetrics: crm-metrics
        errorlogs: error-logs
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      show-components: never
      group:
        crm:
          include: db,liquibaseMigration
  info:
    env:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    description: CRM service for trainers and trainees

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}
