--liquibase formatted sql

--changeset nicat:001-create-users
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255)             NOT NULL,
    last_name  VARCHAR(255)             NOT NULL,
    username   VARCHAR(255) COLLATE "C" NOT NULL,
    password   VARCHAR(255)             NOT NULL,
    is_active  BOOLEAN                  NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

--rollback DROP TABLE users;

