--liquibase formatted sql

--changeset nicat:001-create-users
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(150)             NOT NULL,
    last_name  VARCHAR(150)             NOT NULL,
    username   VARCHAR(310)             NOT NULL,
    password   VARCHAR(60)              NOT NULL,
    is_active  BOOLEAN                  NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

--rollback DROP TABLE users;

