--liquibase formatted sql

--changeset nicat:002-create-training-types
CREATE TABLE training_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

--rollback DROP TABLE training_types;

