--liquibase formatted sql

--changeset nicat:002-create-training-types
CREATE TABLE training_types
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_name UNIQUE (type_name)
);

--rollback DROP TABLE training_types;

