--liquibase formatted sql

--changeset nicat:003-create-trainees
CREATE TABLE trainees
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    date_of_birth DATE,
    address       VARCHAR(255),
    CONSTRAINT uk_trainees_user_id UNIQUE (user_id),
    CONSTRAINT fk_trainees_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

--rollback DROP TABLE trainees;

