--liquibase formatted sql

--changeset nicat:004-create-trainers
CREATE TABLE trainers
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    specialization_id BIGINT NOT NULL,
    CONSTRAINT uk_trainers_user_id UNIQUE (user_id),
    CONSTRAINT fk_trainers_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_trainers_specialization_id
        FOREIGN KEY (specialization_id) REFERENCES training_types (id) ON DELETE RESTRICT
);

--rollback DROP TABLE trainers;

