--liquibase formatted sql

--changeset nicat:005-create-trainings
CREATE TABLE trainings
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    training_type_id    BIGINT       NOT NULL,
    trainee_id          BIGINT       NOT NULL,
    trainer_id          BIGINT       NOT NULL,
    scheduled_date      DATE         NOT NULL,
    duration_in_minutes INTEGER      NOT NULL,
    CONSTRAINT fk_trainings_training_type_id FOREIGN KEY (training_type_id) REFERENCES training_types (id),
    CONSTRAINT fk_trainings_trainee_id FOREIGN KEY (trainee_id) REFERENCES trainees (id),
    CONSTRAINT fk_trainings_trainer_id FOREIGN KEY (trainer_id) REFERENCES trainers (id),
    CONSTRAINT chk_trainings_duration_in_minutes CHECK (duration_in_minutes >= 1)
);

--rollback DROP TABLE trainings;

